import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Zap, Search, FileText, Mail, Bell, Shield } from "lucide-react";

const features = [
  {
    icon: Search,
    title: "Smart Job Search",
    description:
      "Search across multiple job boards simultaneously. Configure locations, job types, and positions to find your perfect match.",
  },
  {
    icon: FileText,
    title: "AI-Tailored CVs",
    description:
      "Your CV is automatically customized for each job application, highlighting the most relevant skills and experience.",
  },
  {
    icon: Mail,
    title: "Auto-Apply",
    description:
      "Applications are sent through your own Gmail account, with personalized cover letters generated by AI.",
  },
  {
    icon: Bell,
    title: "Real-Time Notifications",
    description:
      "Get notified when applications are sent, when companies respond, and when new matching jobs are found.",
  },
  {
    icon: Zap,
    title: "Multiple Profiles",
    description:
      "Run parallel job searches across different locations and positions. Cast a wide net without the manual effort.",
  },
  {
    icon: Shield,
    title: "You Stay in Control",
    description:
      "Set daily limits, review matches before applying, and track every application in your personal dashboard.",
  },
];

export default function LandingPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Navigation */}
      <nav className="sticky top-0 z-50 border-b bg-background/95 backdrop-blur-md">
        <div className="container flex h-16 items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg gradient-primary">
              <Zap className="h-4 w-4 text-primary-foreground" />
            </div>
            <span className="text-lg font-bold">AutoApply</span>
          </Link>
          <div className="flex items-center gap-3">
            <Link href="/login">
              <Button variant="ghost" size="sm">
                Log in
              </Button>
            </Link>
            <Link href="/signup">
              <Button size="sm">Get Started</Button>
            </Link>
          </div>
        </div>
      </nav>

      {/* Hero */}
      <section className="relative gradient-hero">
        <div className="container flex flex-col items-center pt-24 pb-20 text-center">
          <div className="inline-flex items-center gap-2 rounded-full border bg-card px-4 py-1.5 text-sm text-muted-foreground mb-8">
            <Zap className="h-3.5 w-3.5 text-primary" />
            AI-Powered Job Applications
          </div>
          <h1 className="max-w-3xl text-4xl font-extrabold tracking-tight sm:text-5xl lg:text-6xl">
            Stop Applying.{" "}
            <span className="text-gradient">Start Getting Hired.</span>
          </h1>
          <p className="mt-6 max-w-2xl text-lg text-muted-foreground leading-relaxed">
            Upload your CV, tell us what you&apos;re looking for, and AutoApply
            handles the rest. AI-tailored applications sent through your own
            email, across hundreds of job boards.
          </p>
          <div className="mt-10 flex flex-col sm:flex-row gap-4">
            <Link href="/signup">
              <Button size="xl" variant="premium">
                Start Applying for Free
              </Button>
            </Link>
            <Link href="#features">
              <Button size="xl" variant="outline">
                See How It Works
              </Button>
            </Link>
          </div>

          {/* Stats */}
          <div className="mt-20 grid grid-cols-3 gap-8 sm:gap-16">
            {[
              { value: "10K+", label: "Applications Sent" },
              { value: "85%", label: "Match Accuracy" },
              { value: "4.8x", label: "More Interviews" },
            ].map((stat) => (
              <div key={stat.label} className="text-center">
                <p className="text-2xl sm:text-3xl font-bold text-gradient">
                  {stat.value}
                </p>
                <p className="text-sm text-muted-foreground mt-1">
                  {stat.label}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="container py-24">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Everything you need to land your next role
          </h2>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            From job discovery to application tracking, AutoApply automates the
            entire process.
          </p>
        </div>
        <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {features.map((feature) => (
            <div
              key={feature.title}
              className="group rounded-xl border bg-card p-6 transition-all duration-300 hover:shadow-elegant hover:border-primary/20"
            >
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary mb-4 group-hover:bg-primary/15 transition-colors">
                <feature.icon className="h-5 w-5" />
              </div>
              <h3 className="text-base font-semibold mb-2">{feature.title}</h3>
              <p className="text-sm text-muted-foreground leading-relaxed">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* CTA */}
      <section className="border-t">
        <div className="container py-24 text-center">
          <h2 className="text-3xl font-bold tracking-tight sm:text-4xl">
            Ready to automate your job search?
          </h2>
          <p className="mt-4 text-lg text-muted-foreground max-w-xl mx-auto">
            Join thousands of job seekers who are getting more interviews with
            less effort.
          </p>
          <Link href="/signup" className="mt-8 inline-block">
            <Button size="xl" variant="premium">
              Get Started Free
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t py-8">
        <div className="container flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <div className="flex h-6 w-6 items-center justify-center rounded gradient-primary">
              <Zap className="h-3 w-3 text-primary-foreground" />
            </div>
            <span className="text-sm font-semibold">AutoApply</span>
          </div>
          <p className="text-sm text-muted-foreground">
            &copy; {new Date().getFullYear()} AutoApply. All rights reserved.
          </p>
        </div>
      </footer>
    </div>
  );
}
